/**
* @generated Thu Dec 04 2025 14:33:54 GMT-0500 (Eastern Standard Time)

* This file has been generated to create a repository of proto bindings and information so that consumers of the layout engine do not need to
* know or understand fundamental proto constructs. This also insulates developers from changing event specifications.
*
* DO NOT EDIT THIS FILE: It will be regenerated. To make permanent modifications, @see <root>/plugins/proto-event-gen.ts
*/
import { type GenMessage } from "@bufbuild/protobuf/codegenv2";
import { type Message } from "@bufbuild/protobuf";
import { EngineRequestSchema, EngineResponseSchema, type EngineRequest, type EngineResponse } from "../proto/engine_pb";
import { SourcePlayRequestSchema } from "@/proto/widget_pb";
import { SourcePauseRequestSchema } from "@/proto/widget_pb";
import { SourceStopRequestSchema } from "@/proto/widget_pb";
import { InvocationResponseSchema } from "@/proto/engine_pb";
import { LayerAddedSchema } from "@/proto/layer_pb";
import { LayerRemovedSchema } from "@/proto/layer_pb";
import { WidgetAddedSchema } from "@/proto/widget_pb";
import { WidgetRemovedSchema } from "@/proto/widget_pb";
import { WidgetAnimationStartedSchema } from "@/proto/widget_pb";
import { WidgetAnimationCompletedSchema } from "@/proto/widget_pb";
import { WidgetMovedSchema } from "@/proto/widget_pb";
import { WidgetResizedSchema } from "@/proto/widget_pb";
import { EngineShutdownSchema } from "@/proto/engine_pb";

export type EngineRequestProtoMessageTypes = EngineRequest["request"]["value"];
export type EngineRequestProtoTypes = EngineRequest["request"]["case"];
export type EngineResponseProtoMessageTypes = EngineResponse["response"]["value"];
export type EngineResponseProtoTypes = EngineResponse["response"]["case"];
export type EngineProtoTypes = EngineRequestProtoTypes | EngineResponseProtoTypes;
export type EngineMessageTypes = EngineRequestProtoMessageTypes | EngineResponseProtoMessageTypes;
export type EngineRequestEventTypes = "request.source.play" | "request.source.pause" | "request.source.stop";
export type EngineResponseEventTypes = "engine.rpc" | "layer.added" | "layer.removed" | "widget.added" | "widget.removed" | "widget.animation.started" | "widget.animation.completed" | "widget.moved" | "widget.resized" | "engine.shutdown";
export type EngineEventTypes = EngineRequestEventTypes | EngineResponseEventTypes;

export interface EventSchema {
    schema: GenMessage<Message<any>>;
    namespace: "request" | "response";
    parent: GenMessage<Message<any>>;
    name: EngineProtoTypes;
    event: EngineEventTypes;
}

const SourcePlayRequestMapping: EventSchema = {
        schema: SourcePlayRequestSchema,
        namespace: "request",
        parent: EngineRequestSchema,
        name: "sourcePlay",
        event: "request.source.play"
    };
const SourcePauseRequestMapping: EventSchema = {
        schema: SourcePauseRequestSchema,
        namespace: "request",
        parent: EngineRequestSchema,
        name: "sourcePause",
        event: "request.source.pause"
    };
const SourceStopRequestMapping: EventSchema = {
        schema: SourceStopRequestSchema,
        namespace: "request",
        parent: EngineRequestSchema,
        name: "sourceStop",
        event: "request.source.stop"
    };
const InvocationResponseMapping: EventSchema = {
        schema: InvocationResponseSchema,
        namespace: "response",
        parent: EngineResponseSchema,
        name: "invocationResponse",
        event: "engine.rpc"
    };
const LayerAddedMapping: EventSchema = {
        schema: LayerAddedSchema,
        namespace: "response",
        parent: EngineResponseSchema,
        name: "layerAdded",
        event: "layer.added"
    };
const LayerRemovedMapping: EventSchema = {
        schema: LayerRemovedSchema,
        namespace: "response",
        parent: EngineResponseSchema,
        name: "layerRemoved",
        event: "layer.removed"
    };
const WidgetAddedMapping: EventSchema = {
        schema: WidgetAddedSchema,
        namespace: "response",
        parent: EngineResponseSchema,
        name: "widgetAdded",
        event: "widget.added"
    };
const WidgetRemovedMapping: EventSchema = {
        schema: WidgetRemovedSchema,
        namespace: "response",
        parent: EngineResponseSchema,
        name: "widgetRemoved",
        event: "widget.removed"
    };
const WidgetAnimationStartedMapping: EventSchema = {
        schema: WidgetAnimationStartedSchema,
        namespace: "response",
        parent: EngineResponseSchema,
        name: "widgetAnimationStarted",
        event: "widget.animation.started"
    };
const WidgetAnimationCompletedMapping: EventSchema = {
        schema: WidgetAnimationCompletedSchema,
        namespace: "response",
        parent: EngineResponseSchema,
        name: "widgetAnimationComplete",
        event: "widget.animation.completed"
    };
const WidgetMovedMapping: EventSchema = {
        schema: WidgetMovedSchema,
        namespace: "response",
        parent: EngineResponseSchema,
        name: "widgetMoved",
        event: "widget.moved"
    };
const WidgetResizedMapping: EventSchema = {
        schema: WidgetResizedSchema,
        namespace: "response",
        parent: EngineResponseSchema,
        name: "widgetResized",
        event: "widget.resized"
    };
const EngineShutdownMapping: EventSchema = {
        schema: EngineShutdownSchema,
        namespace: "response",
        parent: EngineResponseSchema,
        name: "engineShutdown",
        event: "engine.shutdown"
    };
export const EngineEventMapping = {
        "request.source.play": SourcePlayRequestMapping,
        "request.source.pause": SourcePauseRequestMapping,
        "request.source.stop": SourceStopRequestMapping,
        "engine.rpc": InvocationResponseMapping,
        "layer.added": LayerAddedMapping,
        "layer.removed": LayerRemovedMapping,
        "widget.added": WidgetAddedMapping,
        "widget.removed": WidgetRemovedMapping,
        "widget.animation.started": WidgetAnimationStartedMapping,
        "widget.animation.completed": WidgetAnimationCompletedMapping,
        "widget.moved": WidgetMovedMapping,
        "widget.resized": WidgetResizedMapping,
        "engine.shutdown": EngineShutdownMapping
    };
export const EngineEventInverseMapping = {
        "sourcePlay": SourcePlayRequestMapping,
        "sourcePause": SourcePauseRequestMapping,
        "sourceStop": SourceStopRequestMapping,
        "invocationResponse": InvocationResponseMapping,
        "layerAdded": LayerAddedMapping,
        "layerRemoved": LayerRemovedMapping,
        "widgetAdded": WidgetAddedMapping,
        "widgetRemoved": WidgetRemovedMapping,
        "widgetAnimationStarted": WidgetAnimationStartedMapping,
        "widgetAnimationComplete": WidgetAnimationCompletedMapping,
        "widgetMoved": WidgetMovedMapping,
        "widgetResized": WidgetResizedMapping,
        "engineShutdown": EngineShutdownMapping
    };
