// @generated by protoc-gen-es v2.10.1 with parameter "target=ts"
// @generated from file connector.proto (syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file connector.proto.
 */
export const file_connector: GenFile = /*@__PURE__*/
  fileDesc("Cg9jb25uZWN0b3IucHJvdG8iggEKDFJlZ2lzdHJhdGlvbhIMCgRuYW1lGAEgASgJEiwKBG1vZGUYAiABKA4yHi5SZWdpc3RyYXRpb24uUmVnaXN0cmF0aW9uTW9kZRIKCgJpZBgDIAEoCSIqChBSZWdpc3RyYXRpb25Nb2RlEgoKBkNMSUVOVBAAEgoKBkVOR0lORRABIhgKCkRpc2Nvbm5lY3QSCgoCaWQYASABKAliBnByb3RvMw");

/**
 * @generated from message Registration
 */
export type Registration = Message<"Registration"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: Registration.RegistrationMode mode = 2;
   */
  mode: Registration_RegistrationMode;

  /**
   * @generated from field: string id = 3;
   */
  id: string;
};

/**
 * Describes the message Registration.
 * Use `create(RegistrationSchema)` to create a new message.
 */
export const RegistrationSchema: GenMessage<Registration> = /*@__PURE__*/
  messageDesc(file_connector, 0);

/**
 * @generated from enum Registration.RegistrationMode
 */
export enum Registration_RegistrationMode {
  /**
   * @generated from enum value: CLIENT = 0;
   */
  CLIENT = 0,

  /**
   * @generated from enum value: ENGINE = 1;
   */
  ENGINE = 1,
}

/**
 * Describes the enum Registration.RegistrationMode.
 */
export const Registration_RegistrationModeSchema: GenEnum<Registration_RegistrationMode> = /*@__PURE__*/
  enumDesc(file_connector, 0, 0);

/**
 * @generated from message Disconnect
 */
export type Disconnect = Message<"Disconnect"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message Disconnect.
 * Use `create(DisconnectSchema)` to create a new message.
 */
export const DisconnectSchema: GenMessage<Disconnect> = /*@__PURE__*/
  messageDesc(file_connector, 1);

