// @generated by protoc-gen-es v2.10.1 with parameter "target=ts"
// @generated from file desc.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Subject } from "./event_pb";
import { file_event } from "./event_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file desc.proto.
 */
export const file_desc: GenFile = /*@__PURE__*/
  fileDesc("CgpkZXNjLnByb3RvIjMKCkRlc2NyaXB0b3ISCgoCaWQYASABKAkSGQoHc3ViamVjdBgCIAEoDjIILlN1YmplY3RiBnByb3RvMw", [file_event]);

/**
 * @generated from message Descriptor
 */
export type Descriptor = Message<"Descriptor"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: Subject subject = 2;
   */
  subject: Subject;
};

/**
 * Describes the message Descriptor.
 * Use `create(DescriptorSchema)` to create a new message.
 */
export const DescriptorSchema: GenMessage<Descriptor> = /*@__PURE__*/
  messageDesc(file_desc, 0);

