// @generated by protoc-gen-es v2.10.1 with parameter "target=ts"
// @generated from file engine.proto (syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { LayerAdded, LayerRemoved } from "./layer_pb";
import { file_layer } from "./layer_pb";
import type { Descriptor } from "./desc_pb";
import { file_desc } from "./desc_pb";
import type { SourcePauseRequest, SourcePlayRequest, SourceStopRequest, WidgetAdded, WidgetAnimationCompleted, WidgetAnimationStarted, WidgetMoved, WidgetRemoved, WidgetResized } from "./widget_pb";
import { file_widget } from "./widget_pb";
import { file_event } from "./event_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file engine.proto.
 */
export const file_engine: GenFile = /*@__PURE__*/
  fileDesc("CgxlbmdpbmUucHJvdG8iQAoORW5naW5lU2h1dGRvd24SGQoEZGVzYxgBIAEoCzILLkRlc2NyaXB0b3I6E8K4Ag9lbmdpbmUuc2h1dGRvd24i1wEKDUVuZ2luZVJlcXVlc3QSHAoHdGFyZ2V0cxgBIAMoCzILLkRlc2NyaXB0b3ISGgoEbW9kZRgCIAEoDjIMLlJlcXVlc3RNb2RlEikKC3NvdXJjZV9wbGF5GAogASgLMhIuU291cmNlUGxheVJlcXVlc3RIABIrCgxzb3VyY2VfcGF1c2UYCyABKAsyEy5Tb3VyY2VQYXVzZVJlcXVlc3RIABIpCgtzb3VyY2Vfc3RvcBgMIAEoCzISLlNvdXJjZVN0b3BSZXF1ZXN0SABCCQoHcmVxdWVzdCLmAwoORW5naW5lUmVzcG9uc2USMgoTaW52b2NhdGlvbl9yZXNwb25zZRgyIAEoCzITLkludm9jYXRpb25SZXNwb25zZUgAEiIKC2xheWVyX2FkZGVkGGQgASgLMgsuTGF5ZXJBZGRlZEgAEiYKDWxheWVyX3JlbW92ZWQYZSABKAsyDS5MYXllclJlbW92ZWRIABIkCgx3aWRnZXRfYWRkZWQYZyABKAsyDC5XaWRnZXRBZGRlZEgAEigKDndpZGdldF9yZW1vdmVkGGggASgLMg4uV2lkZ2V0UmVtb3ZlZEgAEjsKGHdpZGdldF9hbmltYXRpb25fc3RhcnRlZBhpIAEoCzIXLldpZGdldEFuaW1hdGlvblN0YXJ0ZWRIABI+Chl3aWRnZXRfYW5pbWF0aW9uX2NvbXBsZXRlGGogASgLMhkuV2lkZ2V0QW5pbWF0aW9uQ29tcGxldGVkSAASJAoMd2lkZ2V0X21vdmVkGGsgASgLMgwuV2lkZ2V0TW92ZWRIABIoCg53aWRnZXRfcmVzaXplZBhsIAEoCzIOLldpZGdldFJlc2l6ZWRIABIrCg9lbmdpbmVfc2h1dGRvd24YyAEgASgLMg8uRW5naW5lU2h1dGRvd25IAEIKCghyZXNwb25zZSJJChJJbnZvY2F0aW9uUmVzcG9uc2USIwoLaW52b2NhdGlvbnMYASADKAsyDi5SUENJbnZvY2F0aW9uOg7CuAIKZW5naW5lLnJwYyKUAQoNUlBDSW52b2NhdGlvbhIbCgZ0YXJnZXQYASABKAsyCy5EZXNjcmlwdG9yEi8KBnN0YXR1cxgCIAEoDjIfLlJQQ0ludm9jYXRpb24uSW52b2NhdGlvblN0YXR1cxINCgVlcnJvchgDIAEoCSImChBJbnZvY2F0aW9uU3RhdHVzEgYKAk9LEAASCgoGRkFJTEVEEAEifQoNRW5naW5lTWVzc2FnZRIZCgRkZXNjGAEgASgLMgsuRGVzY3JpcHRvchIhCgdyZXF1ZXN0GAogASgLMg4uRW5naW5lUmVxdWVzdEgAEiMKCHJlc3BvbnNlGAsgASgLMg8uRW5naW5lUmVzcG9uc2VIAEIJCgdwYXlsb2FkKiYKC1JlcXVlc3RNb2RlEgoKBlNUUklDVBAAEgsKB1JFTEFYRUQQATI9ChBFbmdpbmVScGNTZXJ2aWNlEikKBGNhbGwSDi5FbmdpbmVSZXF1ZXN0Gg8uRW5naW5lUmVzcG9uc2UiAGIGcHJvdG8z", [file_layer, file_desc, file_widget, file_event]);

/**
 * All requests and responses MUST implement the extension event_name from event.proto
 * Failure to do so will cause the engine to fully reject your events.
 *
 * @generated from message EngineShutdown
 */
export type EngineShutdown = Message<"EngineShutdown"> & {
  /**
   * @generated from field: Descriptor desc = 1;
   */
  desc?: Descriptor;
};

/**
 * Describes the message EngineShutdown.
 * Use `create(EngineShutdownSchema)` to create a new message.
 */
export const EngineShutdownSchema: GenMessage<EngineShutdown> = /*@__PURE__*/
  messageDesc(file_engine, 0);

/**
 * @generated from message EngineRequest
 */
export type EngineRequest = Message<"EngineRequest"> & {
  /**
   * @generated from field: repeated Descriptor targets = 1;
   */
  targets: Descriptor[];

  /**
   * @generated from field: RequestMode mode = 2;
   */
  mode: RequestMode;

  /**
   * @generated from oneof EngineRequest.request
   */
  request: {
    /**
     * @generated from field: SourcePlayRequest source_play = 10;
     */
    value: SourcePlayRequest;
    case: "sourcePlay";
  } | {
    /**
     * @generated from field: SourcePauseRequest source_pause = 11;
     */
    value: SourcePauseRequest;
    case: "sourcePause";
  } | {
    /**
     * @generated from field: SourceStopRequest source_stop = 12;
     */
    value: SourceStopRequest;
    case: "sourceStop";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message EngineRequest.
 * Use `create(EngineRequestSchema)` to create a new message.
 */
export const EngineRequestSchema: GenMessage<EngineRequest> = /*@__PURE__*/
  messageDesc(file_engine, 1);

/**
 * @generated from message EngineResponse
 */
export type EngineResponse = Message<"EngineResponse"> & {
  /**
   * @generated from oneof EngineResponse.response
   */
  response: {
    /**
     * @generated from field: InvocationResponse invocation_response = 50;
     */
    value: InvocationResponse;
    case: "invocationResponse";
  } | {
    /**
     * @generated from field: LayerAdded layer_added = 100;
     */
    value: LayerAdded;
    case: "layerAdded";
  } | {
    /**
     * @generated from field: LayerRemoved layer_removed = 101;
     */
    value: LayerRemoved;
    case: "layerRemoved";
  } | {
    /**
     * @generated from field: WidgetAdded widget_added = 103;
     */
    value: WidgetAdded;
    case: "widgetAdded";
  } | {
    /**
     * @generated from field: WidgetRemoved widget_removed = 104;
     */
    value: WidgetRemoved;
    case: "widgetRemoved";
  } | {
    /**
     * @generated from field: WidgetAnimationStarted widget_animation_started = 105;
     */
    value: WidgetAnimationStarted;
    case: "widgetAnimationStarted";
  } | {
    /**
     * @generated from field: WidgetAnimationCompleted widget_animation_complete = 106;
     */
    value: WidgetAnimationCompleted;
    case: "widgetAnimationComplete";
  } | {
    /**
     * @generated from field: WidgetMoved widget_moved = 107;
     */
    value: WidgetMoved;
    case: "widgetMoved";
  } | {
    /**
     * @generated from field: WidgetResized widget_resized = 108;
     */
    value: WidgetResized;
    case: "widgetResized";
  } | {
    /**
     * @generated from field: EngineShutdown engine_shutdown = 200;
     */
    value: EngineShutdown;
    case: "engineShutdown";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message EngineResponse.
 * Use `create(EngineResponseSchema)` to create a new message.
 */
export const EngineResponseSchema: GenMessage<EngineResponse> = /*@__PURE__*/
  messageDesc(file_engine, 2);

/**
 * @generated from message InvocationResponse
 */
export type InvocationResponse = Message<"InvocationResponse"> & {
  /**
   * @generated from field: repeated RPCInvocation invocations = 1;
   */
  invocations: RPCInvocation[];
};

/**
 * Describes the message InvocationResponse.
 * Use `create(InvocationResponseSchema)` to create a new message.
 */
export const InvocationResponseSchema: GenMessage<InvocationResponse> = /*@__PURE__*/
  messageDesc(file_engine, 3);

/**
 * @generated from message RPCInvocation
 */
export type RPCInvocation = Message<"RPCInvocation"> & {
  /**
   * @generated from field: Descriptor target = 1;
   */
  target?: Descriptor;

  /**
   * @generated from field: RPCInvocation.InvocationStatus status = 2;
   */
  status: RPCInvocation_InvocationStatus;

  /**
   * @generated from field: string error = 3;
   */
  error: string;
};

/**
 * Describes the message RPCInvocation.
 * Use `create(RPCInvocationSchema)` to create a new message.
 */
export const RPCInvocationSchema: GenMessage<RPCInvocation> = /*@__PURE__*/
  messageDesc(file_engine, 4);

/**
 * @generated from enum RPCInvocation.InvocationStatus
 */
export enum RPCInvocation_InvocationStatus {
  /**
   * @generated from enum value: OK = 0;
   */
  OK = 0,

  /**
   * @generated from enum value: FAILED = 1;
   */
  FAILED = 1,
}

/**
 * Describes the enum RPCInvocation.InvocationStatus.
 */
export const RPCInvocation_InvocationStatusSchema: GenEnum<RPCInvocation_InvocationStatus> = /*@__PURE__*/
  enumDesc(file_engine, 4, 0);

/**
 * @generated from message EngineMessage
 */
export type EngineMessage = Message<"EngineMessage"> & {
  /**
   * @generated from field: Descriptor desc = 1;
   */
  desc?: Descriptor;

  /**
   * @generated from oneof EngineMessage.payload
   */
  payload: {
    /**
     * @generated from field: EngineRequest request = 10;
     */
    value: EngineRequest;
    case: "request";
  } | {
    /**
     * @generated from field: EngineResponse response = 11;
     */
    value: EngineResponse;
    case: "response";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message EngineMessage.
 * Use `create(EngineMessageSchema)` to create a new message.
 */
export const EngineMessageSchema: GenMessage<EngineMessage> = /*@__PURE__*/
  messageDesc(file_engine, 5);

/**
 * @generated from enum RequestMode
 */
export enum RequestMode {
  /**
   * The default mode. If not all targets are valid (either they do not exist, or no bound method is found for the call), an error will be thrown.
   *
   * @generated from enum value: STRICT = 0;
   */
  STRICT = 0,

  /**
   * Invalid targets are silently ignored
   *
   * @generated from enum value: RELAXED = 1;
   */
  RELAXED = 1,
}

/**
 * Describes the enum RequestMode.
 */
export const RequestModeSchema: GenEnum<RequestMode> = /*@__PURE__*/
  enumDesc(file_engine, 0);

/**
 * @generated from service EngineRpcService
 */
export const EngineRpcService: GenService<{
  /**
   * @generated from rpc EngineRpcService.call
   */
  call: {
    methodKind: "unary";
    input: typeof EngineRequestSchema;
    output: typeof EngineResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_engine, 0);

