// @generated by protoc-gen-es v2.10.1 with parameter "target=ts"
// @generated from file engine.proto (syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { LayerAdded, LayerRemoved } from "./layer_pb";
import { file_layer } from "./layer_pb";
import type { Descriptor } from "./desc_pb";
import { file_desc } from "./desc_pb";
import type { SourcePauseRequest, SourcePlayRequest, SourceStopRequest, WidgetAdded, WidgetAnimationCompleted, WidgetAnimationStarted, WidgetMoved, WidgetRemoved, WidgetResized } from "./widget_pb";
import { file_widget } from "./widget_pb";
import { file_event } from "./event_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file engine.proto.
 */
export const file_engine: GenFile = /*@__PURE__*/
  fileDesc("CgxlbmdpbmUucHJvdG8iQAoORW5naW5lU2h1dGRvd24SGQoEZGVzYxgBIAEoCzILLkRlc2NyaXB0b3I6E8K4Ag9lbmdpbmUuc2h1dGRvd24iEAoEUGluZzoIwrgCBHBpbmciEAoEUG9uZzoIwrgCBHBvbmci7gEKDUVuZ2luZVJlcXVlc3QSHAoHdGFyZ2V0cxgBIAMoCzILLkRlc2NyaXB0b3ISGgoEbW9kZRgCIAEoDjIMLlJlcXVlc3RNb2RlEhUKBHBpbmcYMiABKAsyBS5QaW5nSAASKQoLc291cmNlX3BsYXkYZCABKAsyEi5Tb3VyY2VQbGF5UmVxdWVzdEgAEisKDHNvdXJjZV9wYXVzZRhlIAEoCzITLlNvdXJjZVBhdXNlUmVxdWVzdEgAEikKC3NvdXJjZV9zdG9wGGYgASgLMhIuU291cmNlU3RvcFJlcXVlc3RIAEIJCgdyZXF1ZXN0Iv0DCg5FbmdpbmVSZXNwb25zZRIVCgRwb25nGDIgASgLMgUuUG9uZ0gAEjIKE2ludm9jYXRpb25fcmVzcG9uc2UYMyABKAsyEy5JbnZvY2F0aW9uUmVzcG9uc2VIABIiCgtsYXllcl9hZGRlZBhkIAEoCzILLkxheWVyQWRkZWRIABImCg1sYXllcl9yZW1vdmVkGGUgASgLMg0uTGF5ZXJSZW1vdmVkSAASJAoMd2lkZ2V0X2FkZGVkGGcgASgLMgwuV2lkZ2V0QWRkZWRIABIoCg53aWRnZXRfcmVtb3ZlZBhoIAEoCzIOLldpZGdldFJlbW92ZWRIABI7Chh3aWRnZXRfYW5pbWF0aW9uX3N0YXJ0ZWQYaSABKAsyFy5XaWRnZXRBbmltYXRpb25TdGFydGVkSAASPgoZd2lkZ2V0X2FuaW1hdGlvbl9jb21wbGV0ZRhqIAEoCzIZLldpZGdldEFuaW1hdGlvbkNvbXBsZXRlZEgAEiQKDHdpZGdldF9tb3ZlZBhrIAEoCzIMLldpZGdldE1vdmVkSAASKAoOd2lkZ2V0X3Jlc2l6ZWQYbCABKAsyDi5XaWRnZXRSZXNpemVkSAASKwoPZW5naW5lX3NodXRkb3duGMgBIAEoCzIPLkVuZ2luZVNodXRkb3duSABCCgoIcmVzcG9uc2UiSQoSSW52b2NhdGlvblJlc3BvbnNlEiMKC2ludm9jYXRpb25zGAEgAygLMg4uUlBDSW52b2NhdGlvbjoOwrgCCmVuZ2luZS5ycGMilAEKDVJQQ0ludm9jYXRpb24SGwoGdGFyZ2V0GAEgASgLMgsuRGVzY3JpcHRvchIvCgZzdGF0dXMYAiABKA4yHy5SUENJbnZvY2F0aW9uLkludm9jYXRpb25TdGF0dXMSDQoFZXJyb3IYAyABKAkiJgoQSW52b2NhdGlvblN0YXR1cxIGCgJPSxAAEgoKBkZBSUxFRBABIn0KDUVuZ2luZU1lc3NhZ2USGQoEZGVzYxgBIAEoCzILLkRlc2NyaXB0b3ISIQoHcmVxdWVzdBgKIAEoCzIOLkVuZ2luZVJlcXVlc3RIABIjCghyZXNwb25zZRgLIAEoCzIPLkVuZ2luZVJlc3BvbnNlSABCCQoHcGF5bG9hZComCgtSZXF1ZXN0TW9kZRIKCgZTVFJJQ1QQABILCgdSRUxBWEVEEAEyPQoQRW5naW5lUnBjU2VydmljZRIpCgRjYWxsEg4uRW5naW5lUmVxdWVzdBoPLkVuZ2luZVJlc3BvbnNlIgBiBnByb3RvMw", [file_layer, file_desc, file_widget, file_event]);

/**
 * All requests and responses MUST implement the extension event_name from event.proto
 * Failure to do so will cause the engine to fully reject your events.
 *
 * @generated from message EngineShutdown
 */
export type EngineShutdown = Message<"EngineShutdown"> & {
  /**
   * @generated from field: Descriptor desc = 1;
   */
  desc?: Descriptor;
};

/**
 * Describes the message EngineShutdown.
 * Use `create(EngineShutdownSchema)` to create a new message.
 */
export const EngineShutdownSchema: GenMessage<EngineShutdown> = /*@__PURE__*/
  messageDesc(file_engine, 0);

/**
 * @generated from message Ping
 */
export type Ping = Message<"Ping"> & {
};

/**
 * Describes the message Ping.
 * Use `create(PingSchema)` to create a new message.
 */
export const PingSchema: GenMessage<Ping> = /*@__PURE__*/
  messageDesc(file_engine, 1);

/**
 * @generated from message Pong
 */
export type Pong = Message<"Pong"> & {
};

/**
 * Describes the message Pong.
 * Use `create(PongSchema)` to create a new message.
 */
export const PongSchema: GenMessage<Pong> = /*@__PURE__*/
  messageDesc(file_engine, 2);

/**
 * @generated from message EngineRequest
 */
export type EngineRequest = Message<"EngineRequest"> & {
  /**
   * @generated from field: repeated Descriptor targets = 1;
   */
  targets: Descriptor[];

  /**
   * @generated from field: RequestMode mode = 2;
   */
  mode: RequestMode;

  /**
   * @generated from oneof EngineRequest.request
   */
  request: {
    /**
     * @generated from field: Ping ping = 50;
     */
    value: Ping;
    case: "ping";
  } | {
    /**
     * @generated from field: SourcePlayRequest source_play = 100;
     */
    value: SourcePlayRequest;
    case: "sourcePlay";
  } | {
    /**
     * @generated from field: SourcePauseRequest source_pause = 101;
     */
    value: SourcePauseRequest;
    case: "sourcePause";
  } | {
    /**
     * @generated from field: SourceStopRequest source_stop = 102;
     */
    value: SourceStopRequest;
    case: "sourceStop";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message EngineRequest.
 * Use `create(EngineRequestSchema)` to create a new message.
 */
export const EngineRequestSchema: GenMessage<EngineRequest> = /*@__PURE__*/
  messageDesc(file_engine, 3);

/**
 * @generated from message EngineResponse
 */
export type EngineResponse = Message<"EngineResponse"> & {
  /**
   * @generated from oneof EngineResponse.response
   */
  response: {
    /**
     * @generated from field: Pong pong = 50;
     */
    value: Pong;
    case: "pong";
  } | {
    /**
     * @generated from field: InvocationResponse invocation_response = 51;
     */
    value: InvocationResponse;
    case: "invocationResponse";
  } | {
    /**
     * @generated from field: LayerAdded layer_added = 100;
     */
    value: LayerAdded;
    case: "layerAdded";
  } | {
    /**
     * @generated from field: LayerRemoved layer_removed = 101;
     */
    value: LayerRemoved;
    case: "layerRemoved";
  } | {
    /**
     * @generated from field: WidgetAdded widget_added = 103;
     */
    value: WidgetAdded;
    case: "widgetAdded";
  } | {
    /**
     * @generated from field: WidgetRemoved widget_removed = 104;
     */
    value: WidgetRemoved;
    case: "widgetRemoved";
  } | {
    /**
     * @generated from field: WidgetAnimationStarted widget_animation_started = 105;
     */
    value: WidgetAnimationStarted;
    case: "widgetAnimationStarted";
  } | {
    /**
     * @generated from field: WidgetAnimationCompleted widget_animation_complete = 106;
     */
    value: WidgetAnimationCompleted;
    case: "widgetAnimationComplete";
  } | {
    /**
     * @generated from field: WidgetMoved widget_moved = 107;
     */
    value: WidgetMoved;
    case: "widgetMoved";
  } | {
    /**
     * @generated from field: WidgetResized widget_resized = 108;
     */
    value: WidgetResized;
    case: "widgetResized";
  } | {
    /**
     * @generated from field: EngineShutdown engine_shutdown = 200;
     */
    value: EngineShutdown;
    case: "engineShutdown";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message EngineResponse.
 * Use `create(EngineResponseSchema)` to create a new message.
 */
export const EngineResponseSchema: GenMessage<EngineResponse> = /*@__PURE__*/
  messageDesc(file_engine, 4);

/**
 * @generated from message InvocationResponse
 */
export type InvocationResponse = Message<"InvocationResponse"> & {
  /**
   * @generated from field: repeated RPCInvocation invocations = 1;
   */
  invocations: RPCInvocation[];
};

/**
 * Describes the message InvocationResponse.
 * Use `create(InvocationResponseSchema)` to create a new message.
 */
export const InvocationResponseSchema: GenMessage<InvocationResponse> = /*@__PURE__*/
  messageDesc(file_engine, 5);

/**
 * @generated from message RPCInvocation
 */
export type RPCInvocation = Message<"RPCInvocation"> & {
  /**
   * @generated from field: Descriptor target = 1;
   */
  target?: Descriptor;

  /**
   * @generated from field: RPCInvocation.InvocationStatus status = 2;
   */
  status: RPCInvocation_InvocationStatus;

  /**
   * @generated from field: string error = 3;
   */
  error: string;
};

/**
 * Describes the message RPCInvocation.
 * Use `create(RPCInvocationSchema)` to create a new message.
 */
export const RPCInvocationSchema: GenMessage<RPCInvocation> = /*@__PURE__*/
  messageDesc(file_engine, 6);

/**
 * @generated from enum RPCInvocation.InvocationStatus
 */
export enum RPCInvocation_InvocationStatus {
  /**
   * @generated from enum value: OK = 0;
   */
  OK = 0,

  /**
   * @generated from enum value: FAILED = 1;
   */
  FAILED = 1,
}

/**
 * Describes the enum RPCInvocation.InvocationStatus.
 */
export const RPCInvocation_InvocationStatusSchema: GenEnum<RPCInvocation_InvocationStatus> = /*@__PURE__*/
  enumDesc(file_engine, 6, 0);

/**
 * @generated from message EngineMessage
 */
export type EngineMessage = Message<"EngineMessage"> & {
  /**
   * @generated from field: Descriptor desc = 1;
   */
  desc?: Descriptor;

  /**
   * @generated from oneof EngineMessage.payload
   */
  payload: {
    /**
     * @generated from field: EngineRequest request = 10;
     */
    value: EngineRequest;
    case: "request";
  } | {
    /**
     * @generated from field: EngineResponse response = 11;
     */
    value: EngineResponse;
    case: "response";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message EngineMessage.
 * Use `create(EngineMessageSchema)` to create a new message.
 */
export const EngineMessageSchema: GenMessage<EngineMessage> = /*@__PURE__*/
  messageDesc(file_engine, 7);

/**
 * @generated from enum RequestMode
 */
export enum RequestMode {
  /**
   * The default mode. If not all targets are valid (either they do not exist, or no bound method is found for the call), an error will be thrown.
   *
   * @generated from enum value: STRICT = 0;
   */
  STRICT = 0,

  /**
   * Invalid targets are silently ignored
   *
   * @generated from enum value: RELAXED = 1;
   */
  RELAXED = 1,
}

/**
 * Describes the enum RequestMode.
 */
export const RequestModeSchema: GenEnum<RequestMode> = /*@__PURE__*/
  enumDesc(file_engine, 0);

/**
 * @generated from service EngineRpcService
 */
export const EngineRpcService: GenService<{
  /**
   * @generated from rpc EngineRpcService.call
   */
  call: {
    methodKind: "unary";
    input: typeof EngineRequestSchema;
    output: typeof EngineResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_engine, 0);

