// @generated by protoc-gen-es v2.10.1 with parameter "target=ts"
// @generated from file event.proto (syntax proto3)
/* eslint-disable */

import type { GenEnum, GenExtension, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, extDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";
import type { MessageOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file event.proto.
 */
export const file_event: GenFile = /*@__PURE__*/
  fileDesc("CgtldmVudC5wcm90byosCgdTdWJqZWN0EgoKBldJREdFVBAAEgkKBUxBWUVSEAESCgoGRU5HSU5FEAI6PwoKZXZlbnRfbmFtZRIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxiIJyABKAlSCWV2ZW50TmFtZTpECgd0YXJnZXRzEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGIknIAMoDjIILlN1YmplY3RSB3RhcmdldHNiBnByb3RvMw", [file_google_protobuf_descriptor]);

/**
 * @generated from enum Subject
 */
export enum Subject {
  /**
   * The default subject. If not specified, this will target a widget ID
   *
   * @generated from enum value: WIDGET = 0;
   */
  WIDGET = 0,

  /**
   * Targets a layer.
   *
   * @generated from enum value: LAYER = 1;
   */
  LAYER = 1,

  /**
   * Targets the engine.
   *
   * @generated from enum value: ENGINE = 2;
   */
  ENGINE = 2,
}

/**
 * Describes the enum Subject.
 */
export const SubjectSchema: GenEnum<Subject> = /*@__PURE__*/
  enumDesc(file_event, 0);

/**
 * @generated from extension: string event_name = 5000;
 */
export const event_name: GenExtension<MessageOptions, string> = /*@__PURE__*/
  extDesc(file_event, 0);

/**
 * @generated from extension: repeated Subject targets = 5001;
 */
export const targets: GenExtension<MessageOptions, Subject[]> = /*@__PURE__*/
  extDesc(file_event, 1);

