// @generated by protoc-gen-es v2.10.1 with parameter "target=ts"
// @generated from file layer.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_event } from "./event_pb";
import type { Descriptor } from "./desc_pb";
import { file_desc } from "./desc_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file layer.proto.
 */
export const file_layer: GenFile = /*@__PURE__*/
  fileDesc("CgtsYXllci5wcm90byI4CgpMYXllckFkZGVkEhkKBGRlc2MYASABKAsyCy5EZXNjcmlwdG9yOg/CuAILbGF5ZXIuYWRkZWQiPAoMTGF5ZXJSZW1vdmVkEhkKBGRlc2MYASABKAsyCy5EZXNjcmlwdG9yOhHCuAINbGF5ZXIucmVtb3ZlZGIGcHJvdG8z", [file_event, file_desc]);

/**
 * @generated from message LayerAdded
 */
export type LayerAdded = Message<"LayerAdded"> & {
  /**
   * @generated from field: Descriptor desc = 1;
   */
  desc?: Descriptor;
};

/**
 * Describes the message LayerAdded.
 * Use `create(LayerAddedSchema)` to create a new message.
 */
export const LayerAddedSchema: GenMessage<LayerAdded> = /*@__PURE__*/
  messageDesc(file_layer, 0);

/**
 * @generated from message LayerRemoved
 */
export type LayerRemoved = Message<"LayerRemoved"> & {
  /**
   * @generated from field: Descriptor desc = 1;
   */
  desc?: Descriptor;
};

/**
 * Describes the message LayerRemoved.
 * Use `create(LayerRemovedSchema)` to create a new message.
 */
export const LayerRemovedSchema: GenMessage<LayerRemoved> = /*@__PURE__*/
  messageDesc(file_layer, 1);

