// @generated by protoc-gen-es v2.10.1 with parameter "target=ts"
// @generated from file widget.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_event } from "./event_pb";
import type { Descriptor } from "./desc_pb";
import { file_desc } from "./desc_pb";
import { file_google_protobuf_any } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file widget.proto.
 */
export const file_widget: GenFile = /*@__PURE__*/
  fileDesc("Cgx3aWRnZXQucHJvdG8iewoNV2lkZ2V0UmVzaXplZBIaCgVsYXllchgBIAEoCzILLkRlc2NyaXB0b3ISGwoGd2lkZ2V0GAIgASgLMgsuRGVzY3JpcHRvchINCgV3aWR0aBgDIAEoBRIOCgZoZWlnaHQYBCABKAU6EsK4Ag53aWRnZXQucmVzaXplZCJuCgtXaWRnZXRNb3ZlZBIaCgVsYXllchgBIAEoCzILLkRlc2NyaXB0b3ISGwoGd2lkZ2V0GAIgASgLMgsuRGVzY3JpcHRvchIJCgF4GAMgASgFEgkKAXkYBCABKAU6EMK4Agx3aWRnZXQubW92ZWQibwoWV2lkZ2V0QW5pbWF0aW9uU3RhcnRlZBIaCgVsYXllchgBIAEoCzILLkRlc2NyaXB0b3ISGwoGd2lkZ2V0GAIgASgLMgsuRGVzY3JpcHRvcjocwrgCGHdpZGdldC5hbmltYXRpb24uc3RhcnRlZCJzChhXaWRnZXRBbmltYXRpb25Db21wbGV0ZWQSGgoFbGF5ZXIYASABKAsyCy5EZXNjcmlwdG9yEhsKBndpZGdldBgCIAEoCzILLkRlc2NyaXB0b3I6HsK4Ahp3aWRnZXQuYW5pbWF0aW9uLmNvbXBsZXRlZCJmCgtXaWRnZXRBZGRlZBIaCgVsYXllchgBIAEoCzILLkRlc2NyaXB0b3ISGwoGd2lkZ2V0GAIgASgLMgsuRGVzY3JpcHRvchIMCgR0eXBlGAMgASgJOhDCuAIMd2lkZ2V0LmFkZGVkIlwKDVdpZGdldFJlbW92ZWQSGgoFbGF5ZXIYASABKAsyCy5EZXNjcmlwdG9yEhsKBndpZGdldBgCIAEoCzILLkRlc2NyaXB0b3I6EsK4Ag53aWRnZXQucmVtb3ZlZCIsChFTb3VyY2VQbGF5UmVxdWVzdDoXwrgCE3JlcXVlc3Quc291cmNlLnBsYXkiLgoSU291cmNlUGF1c2VSZXF1ZXN0OhjCuAIUcmVxdWVzdC5zb3VyY2UucGF1c2UiLAoRU291cmNlU3RvcFJlcXVlc3Q6F8K4AhNyZXF1ZXN0LnNvdXJjZS5zdG9wYgZwcm90bzM", [file_event, file_desc, file_google_protobuf_any]);

/**
 * @generated from message WidgetResized
 */
export type WidgetResized = Message<"WidgetResized"> & {
  /**
   * @generated from field: Descriptor layer = 1;
   */
  layer?: Descriptor;

  /**
   * @generated from field: Descriptor widget = 2;
   */
  widget?: Descriptor;

  /**
   * @generated from field: int32 width = 3;
   */
  width: number;

  /**
   * @generated from field: int32 height = 4;
   */
  height: number;
};

/**
 * Describes the message WidgetResized.
 * Use `create(WidgetResizedSchema)` to create a new message.
 */
export const WidgetResizedSchema: GenMessage<WidgetResized> = /*@__PURE__*/
  messageDesc(file_widget, 0);

/**
 * @generated from message WidgetMoved
 */
export type WidgetMoved = Message<"WidgetMoved"> & {
  /**
   * @generated from field: Descriptor layer = 1;
   */
  layer?: Descriptor;

  /**
   * @generated from field: Descriptor widget = 2;
   */
  widget?: Descriptor;

  /**
   * @generated from field: int32 x = 3;
   */
  x: number;

  /**
   * @generated from field: int32 y = 4;
   */
  y: number;
};

/**
 * Describes the message WidgetMoved.
 * Use `create(WidgetMovedSchema)` to create a new message.
 */
export const WidgetMovedSchema: GenMessage<WidgetMoved> = /*@__PURE__*/
  messageDesc(file_widget, 1);

/**
 * @generated from message WidgetAnimationStarted
 */
export type WidgetAnimationStarted = Message<"WidgetAnimationStarted"> & {
  /**
   * @generated from field: Descriptor layer = 1;
   */
  layer?: Descriptor;

  /**
   * @generated from field: Descriptor widget = 2;
   */
  widget?: Descriptor;
};

/**
 * Describes the message WidgetAnimationStarted.
 * Use `create(WidgetAnimationStartedSchema)` to create a new message.
 */
export const WidgetAnimationStartedSchema: GenMessage<WidgetAnimationStarted> = /*@__PURE__*/
  messageDesc(file_widget, 2);

/**
 * @generated from message WidgetAnimationCompleted
 */
export type WidgetAnimationCompleted = Message<"WidgetAnimationCompleted"> & {
  /**
   * @generated from field: Descriptor layer = 1;
   */
  layer?: Descriptor;

  /**
   * @generated from field: Descriptor widget = 2;
   */
  widget?: Descriptor;
};

/**
 * Describes the message WidgetAnimationCompleted.
 * Use `create(WidgetAnimationCompletedSchema)` to create a new message.
 */
export const WidgetAnimationCompletedSchema: GenMessage<WidgetAnimationCompleted> = /*@__PURE__*/
  messageDesc(file_widget, 3);

/**
 * @generated from message WidgetAdded
 */
export type WidgetAdded = Message<"WidgetAdded"> & {
  /**
   * @generated from field: Descriptor layer = 1;
   */
  layer?: Descriptor;

  /**
   * @generated from field: Descriptor widget = 2;
   */
  widget?: Descriptor;

  /**
   * @generated from field: string type = 3;
   */
  type: string;
};

/**
 * Describes the message WidgetAdded.
 * Use `create(WidgetAddedSchema)` to create a new message.
 */
export const WidgetAddedSchema: GenMessage<WidgetAdded> = /*@__PURE__*/
  messageDesc(file_widget, 4);

/**
 * @generated from message WidgetRemoved
 */
export type WidgetRemoved = Message<"WidgetRemoved"> & {
  /**
   * @generated from field: Descriptor layer = 1;
   */
  layer?: Descriptor;

  /**
   * @generated from field: Descriptor widget = 2;
   */
  widget?: Descriptor;
};

/**
 * Describes the message WidgetRemoved.
 * Use `create(WidgetRemovedSchema)` to create a new message.
 */
export const WidgetRemovedSchema: GenMessage<WidgetRemoved> = /*@__PURE__*/
  messageDesc(file_widget, 5);

/**
 * @generated from message SourcePlayRequest
 */
export type SourcePlayRequest = Message<"SourcePlayRequest"> & {
};

/**
 * Describes the message SourcePlayRequest.
 * Use `create(SourcePlayRequestSchema)` to create a new message.
 */
export const SourcePlayRequestSchema: GenMessage<SourcePlayRequest> = /*@__PURE__*/
  messageDesc(file_widget, 6);

/**
 * @generated from message SourcePauseRequest
 */
export type SourcePauseRequest = Message<"SourcePauseRequest"> & {
};

/**
 * Describes the message SourcePauseRequest.
 * Use `create(SourcePauseRequestSchema)` to create a new message.
 */
export const SourcePauseRequestSchema: GenMessage<SourcePauseRequest> = /*@__PURE__*/
  messageDesc(file_widget, 7);

/**
 * @generated from message SourceStopRequest
 */
export type SourceStopRequest = Message<"SourceStopRequest"> & {
};

/**
 * Describes the message SourceStopRequest.
 * Use `create(SourceStopRequestSchema)` to create a new message.
 */
export const SourceStopRequestSchema: GenMessage<SourceStopRequest> = /*@__PURE__*/
  messageDesc(file_widget, 8);

